vrrp_script check_haproxy {
    script "killall -0 haproxy"
    interval 2
    weight 2
}

vrrp_sync_group VG_1 {
    group {
        VI_LAN
        VI_DMZ
    }
}

vrrp_instance VI_LAN {
    state BACKUP
    interface enp0s8          # Interface HA-LAN
    virtual_router_id 10
    priority 100              # Priorité inférieure à LB1
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass secret12
    }

    virtual_ipaddress {
        192.168.10.100/24
    }

    track_script {
        check_haproxy
    }
}
vrrp_instance VI_DMZ {
    state BACKUP
    interface enp0s9          # Interface HA-DMZ
    virtual_router_id 20
    priority 100              # Priorité inférieure à LB1
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass secret12
    }

    virtual_ipaddress {
        192.168.20.100/24
    }

    track_script {
        check_haproxy
    }
}

vrrp_instance VI_DMZ {
    state BACKUP
    interface enp0s9          # Interface HA-DMZ
    virtual_router_id 20
    priority 100              # Priorité inférieure à LB1
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass secret12
    }

    virtual_ipaddress {
        192.168.20.100/24
    }

    track_script {
        check_haproxy
    }
}

vrrp_instance VI_DMZ {
    state BACKUP
    interface enp0s9          # Interface HA-DMZ
    virtual_router_id 20
    priority 100              # Priorité inférieure à LB1
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass secret12
    }

    virtual_ipaddress {
        192.168.20.100/24
    }

    track_script {
        check_haproxy
    }
}

